-- USE housing;

CREATE TABLE IF NOT EXISTS officer (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type ENUM('GOVERNMENT', 'EXTERNAL') NOT NULL,
  name VARCHAR(200) NOT NULL,
  contact_number VARCHAR(50),
  position VARCHAR(150) DEFAULT NULL,
  payment DECIMAL(10,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
